version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: mighty_blade_db
    environment:
      POSTGRES_DB: mighty_blade_api
      POSTGRES_USER: mighty_user
      POSTGRES_PASSWORD: mighty_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: